services:
  app:
    container_name: videostore_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - .:/var/www/html
    ports:
      - '9000:9000'
    depends_on:
      - mysql
    networks:
      - videostore

  mysql:
    container_name: videostore_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    networks:
      - videostore

  nginx:
    container_name: videostore_nginx
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.videostore.rule=Host(`algebra.local`)"
      - "traefik.http.routers.videostore.entrypoints=web"
      - "traefik.http.routers.videostore-secure.rule=Host(`algebra.adicio.hr`)"
      - "traefik.http.routers.videostore-secure.entrypoints=web-secure"
      - "traefik.http.routers.videostore-secure.tls=true"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - mysql
    networks:
      - proxy
      - videostore

volumes:
  db_data:
    driver: local

networks:
  proxy:
    external: true
  videostore: